name: chatrtc
services:
    backend:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        container_name: backend
        restart: always
        ports:
            - 3000:3000

    frontend:
        build:
            context: ./client
            dockerfile: ./Dockerfile
        container_name: frontend
        restart: always
        ports:
            - 8080:3000
