export const enum SocketEventsType {
	CREATE_ROOM = 'CREATE_ROOM',
	CREATED_ROOM = 'CREATED_ROOM',
	CREATE_ERROR_ROOM = 'CREATE_ERROR_ROOM',
	CONNECT_TO_ROOM = 'CONNECT_TO_ROOM',
	CONNECT_ERROR_ROOM = 'CONNECT_ERROR_ROOM',
	DISCONNECT_OF_ROOM = 'DISCONNECT_OF_ROOM',
	GET_LIST_ROOMS = 'GET_LIST_ROOMS',
	SHARE_ROOMS = 'SHARE_ROOMS'
}
