export const enum SocketEvents {
	CREATE_ROOM = 'CREATE_ROOM',
	CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR',
	CREATED_ROOM = 'CREATED_ROOM',
	CONNECT_TO_ROOM = 'CONNECT_TO_ROOM',
	CONNECT_TO_ROOM_ERROR = 'CONNECT_TO_ROOM_ERROR',
	DISCONNECT_OF_ROOM = 'DISCONNECT_OF_ROOM',
	GET_LIST_ROOMS = 'GET_LIST_ROOMS',
	SHARE_ROOMS = 'SHARE_ROOMS',
	ADD_PEER = 'ADD_PEER',
	REMOVE_PEER = 'REMOVE_PEER',
	SHARE_SDP_OFFER = 'SHARE_SDP_OFFER',
	SHARE_SDP_ANSWER = 'SHARE_SDP_ANSWER',
	SHARE_ICE_CANDIDATE = 'SHARE_ICE_CANDIDATE'
}
