export const AUTH_CHECK = 'AUTH_CHECK';
export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const PRELOADER_SIGNIN_SHOW = 'PRELOADER_SIGNIN_SHOW';
export const PRELOADER_SIGNIN_HIDE = 'PRELOADER_SIGNIN_HIDE';